# Generated by Django 5.2.3 on 2025-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentInventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount_used', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('uset_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'appointment_inventory',
                'db_table_comment': 'table of items used in an appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('attention_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('en revision', 'En Revisión'), ('referido', 'Referido'), ('abandonado', 'Abandonado'), ('cancelado', 'Cancelado')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'db_table_comment': 'table of appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'appointment_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalCases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('en revision', 'En Revisión'), ('referido', 'Referido'), ('abandonado', 'Abandonado'), ('cancelado', 'Cancelado')], max_length=20, null=True)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('initial_diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('final_diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('treatment_plan', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinical_cases',
                'db_table_comment': 'table of clinical cases in zafari dental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolutionNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'evolution_notes',
                'db_table_comment': 'table of notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evolutions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_evolution', models.CharField(blank=True, max_length=200, null=True)),
                ('percent_advance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'evolutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolutionTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'evolution_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'note_images',
                'db_table_comment': 'table of images from notes',
                'managed': False,
            },
        ),
    ]
