# Generated by Django 5.2.3 on 2025-07-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_cases', '0002_delete_appointmentinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('activations', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'procedures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('procedure_id', models.ForeignKey(db_column='procedure_id', on_delete=django.db.models.deletion.CASCADE, to='clinical_cases.procedures')),
            ],
        ),
    ]
