# Generated by Django 5.2.3 on 2025-07-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_cases', '0003_procedures_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'managed': False},
        ),
    ]
