# Generated by Django 5.2.3 on 2025-07-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_cases', '0004_alter_activities_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activities',
            table='activities',
        ),
    ]
